
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Define our database schema types
export type Database = {
  public: {
    Tables: {
      quotations: {
        Row: {
          id: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string | null;
          customer_address: string | null;
          date: string;
          total: number;
          status: string;
          items: any;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          customer_name: string;
          customer_email: string;
          customer_phone?: string | null;
          customer_address?: string | null;
          date: string;
          total: number;
          status: string;
          items: any;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          customer_email?: string;
          customer_phone?: string | null;
          customer_address?: string | null;
          date?: string;
          total?: number;
          status?: string;
          items?: any;
          notes?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

const SUPABASE_URL = "https://umlgewufyusmuyrhhfsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbGdld3VmeXVzbXV5cmhoZnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTM1NTgsImV4cCI6MjA2MDEyOTU1OH0._gI-jeQG7BSHk_bI0uoelo6Ysg2GXE-XQXivqwI0MXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
