// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlgewufyusmuyrhhfsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbGdld3VmeXVzbXV5cmhoZnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTM1NTgsImV4cCI6MjA2MDEyOTU1OH0._gI-jeQG7BSHk_bI0uoelo6Ysg2GXE-XQXivqwI0MXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);