
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Define our database schema types
export type Database = {
  public: {
    Tables: {
      quotations: {
        Row: {
          id: string;
          customer_name: string;
          customer_email: string;
          customer_phone: string | null;
          customer_address: string | null;
          date: string;
          total: number;
          status: string;
          items: any;
          notes: string | null;
          created_at: string;
          created_by: string;
        };
        Insert: {
          id: string;
          customer_name: string;
          customer_email: string;
          customer_phone?: string | null;
          customer_address?: string | null;
          date: string;
          total: number;
          status: string;
          items: any;
          notes?: string | null;
          created_at?: string;
          created_by: string;
        };
        Update: {
          id?: string;
          customer_name?: string;
          customer_email?: string;
          customer_phone?: string | null;
          customer_address?: string | null;
          date?: string;
          total?: number;
          status?: string;
          items?: any;
          notes?: string | null;
          created_at?: string;
          created_by?: string;
        };
      };
      products: {
        Row: {
          id: number;
          name: string;
          category: string;
          series: string | null;
          base_rate: number;
          unit_type: string;
          description: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          category: string;
          series?: string | null;
          base_rate: number;
          unit_type: string;
          description?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          category?: string;
          series?: string | null;
          base_rate?: number;
          unit_type?: string;
          description?: string | null;
        };
      };
      series: {
        Row: {
          id: number;
          name: string;
          profile_weight: number;
          material_rate: number;
        };
        Insert: {
          id?: number;
          name: string;
          profile_weight: number;
          material_rate: number;
        };
        Update: {
          id?: number;
          name?: string;
          profile_weight?: number;
          material_rate?: number;
        };
      };
      glass: {
        Row: {
          id: number;
          type: string;
          thickness: number;
          rate: number;
        };
        Insert: {
          id?: number;
          type: string;
          thickness: number;
          rate: number;
        };
        Update: {
          id?: number;
          type?: string;
          thickness?: number;
          rate?: number;
        };
      };
      admin_settings: {
        Row: {
          id: number;
          wastage_percentage: number;
          tax_percentage: number;
          labor_percentage: number;
          logo: string | null;
        };
        Insert: {
          id?: number;
          wastage_percentage: number;
          tax_percentage: number;
          labor_percentage: number;
          logo?: string | null;
        };
        Update: {
          id?: number;
          wastage_percentage?: number;
          tax_percentage?: number;
          labor_percentage?: number;
          logo?: string | null;
        };
      };
      admin_users: {
        Row: {
          id: number;
          name: string;
          email: string;
          role: string;
          status: string;
        };
        Insert: {
          id?: number;
          name: string;
          email: string;
          role: string;
          status: string;
        };
        Update: {
          id?: number;
          name?: string;
          email?: string;
          role?: string;
          status?: string;
        };
      };
      transactions: {
        Row: {
          id: number;
          date: string;
          customer_name: string;
          item_purchased: string;
          quantity: number;
          total: number;
        };
        Insert: {
          id?: number;
          date: string;
          customer_name: string;
          item_purchased: string;
          quantity: number;
          total: number;
        };
        Update: {
          id?: number;
          date?: string;
          customer_name?: string;
          item_purchased?: string;
          quantity?: number;
          total?: number;
        };
      };
      activity_log: {
        Row: {
          id: number;
          user_name: string;
          action: string;
          timestamp: string;
        };
        Insert: {
          id?: number;
          user_name: string;
          action: string;
          timestamp?: string;
        };
        Update: {
          id?: number;
          user_name?: string;
          action?: string;
          timestamp?: string;
        };
      };
      crm: {
        Row: {
          id: number;
          customer_name: string;
          email: string;
          phone_number: string | null;
          address: string | null;
          interaction_notes: string | null;
        };
        Insert: {
          id?: number;
          customer_name: string;
          email: string;
          phone_number?: string | null;
          address?: string | null;
          interaction_notes?: string | null;
        };
        Update: {
          id?: number;
          customer_name?: string;
          email?: string;
          phone_number?: string | null;
          address?: string | null;
          interaction_notes?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          updated_at?: string | null;
        };
      };
      notifications: {
        Row: {
          id: string;
          created_at: string | null;
          user_id: string;
          read: boolean | null;
          message: string;
        };
        Insert: {
          id?: string;
          created_at?: string | null;
          user_id: string;
          read?: boolean | null;
          message: string;
        };
        Update: {
          id?: string;
          created_at?: string | null;
          user_id?: string;
          read?: boolean | null;
          message?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

const SUPABASE_URL = "https://umlgewufyusmuyrhhfsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbGdld3VmeXVzbXV5cmhoZnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTM1NTgsImV4cCI6MjA2MDEyOTU1OH0._gI-jeQG7BSHk_bI0uoelo6Ysg2GXE-XQXivqwI0MXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
